def format_notes(summary_text: str) -> str:
    """
    Formats the summarized text into a clean, structured set of study notes.
    :param summary_text : Gets summary generated by BART model
    :returns: clean, structured set of study notes
    """
    notes = "📚 Lecture Summary Notes 📚\n\n"
    notes += "📝 Summary:\n"
    notes += summary_text.strip() + "\n\n"

    sentences = summary_text.split(". ")

    notes += "🔑 Key Points:\n"
    for sentence in sentences:
        clean_sentence = sentence.strip()
        if len(clean_sentence) > 5:
            if not clean_sentence.endswith("."):
                clean_sentence += "."
            notes += f"- {clean_sentence}\n"

    return notes